---
title: "TBI"
author: "Edwin Zhu"
date: "May 12, 2020"
output: html_document
---

```{r, echo=FALSE}
# Setting up appropriate tables

library(readxl)
library(ggpubr)
library(tidyr)
library(dplyr)
library(fuzzyjoin)
setwd("C:/Users/edwin/Desktop/Volunteer")
data_path = "C:/Users/edwin/Desktop/Volunteer/CANTBI DTI JHU stats.xlsx"
WMF = read_excel(path=data_path, sheet="WMF")
names(WMF) = as.matrix(WMF[1,])
WMF = WMF[-1,]
WMF[] = lapply(WMF, function(x) as.character(x))
WMF = as.data.frame(WMF)

WMF_skeleton = WMF[1:148,]
WMF_skeleton$type = ifelse(grepl("A$", WMF_skeleton$subject), "baseline", "6_week")
# Change the order for type
# Now baseline is the first box in boxplot
WMF_skeleton$type = factor(WMF_skeleton$type, levels = c("baseline","6_week"))
WMF_brain = WMF[152:299,]
WMF_brain$type = ifelse(grepl("A$", WMF_brain$subject), "baseline", "6_week")
# Change the order for type
# Now baseline is the first box in boxplot
WMF_brain$type = factor(WMF_skeleton$type, levels = c("baseline","6_week"))
WMF_skeleton_ROI = WMF_skeleton[,c(1:50,73)]
WMF_skeleton_Tract = WMF_skeleton[,c(1,52:73)]
WMF_brain_ROI = WMF_skeleton[,c(1:50,73)]
WMF_brain_Tract = WMF_skeleton[,c(1,52:73)]
# Split the dataset into 4 separate datasets
# Skeleton tract and ROI and brain ROI and tract
# Create new column that categorizes each row as either baseline or a 6 week patient

WMF_skeleton_ROIbaseline = WMF_skeleton_ROI[grep("A$", WMF_skeleton_ROI$subject),]
WMF_skeleton_ROI6week = WMF_skeleton_ROI[grep("B$", WMF_skeleton_ROI$subject),]
# Split skeleton ROI table into two tables based on baseline or 6 week

# WMF_skeleton
# WMF_skeleton_baseline[]
# WMF_skeleton_6week[]
```

```{r, echo=FALSE}
# basic use of shapiro test and plotting
# Does not include sex and age
# Does not separate test and base cases

ggplot (WMF_skeleton_ROIbaseline, aes(x=as.numeric(`All ROIs`))) + geom_histogram(color="black", fill="white")
# ggdensity(as.numeric(WMF_skeleton_ROIbaseline$`All ROIs`), main = "test")
shapiro.test(as.numeric(WMF_skeleton_ROIbaseline$`All ROIs`))
# P-value > 0.05 assume normality

ggplot (WMF_skeleton_ROI6week, aes(x=as.numeric(`All ROIs`))) + geom_histogram(color="black", fill="white")
shapiro.test(as.numeric(WMF_skeleton_ROI6week$`All ROIs`))
# Assume normality

t.test((as.numeric(WMF_skeleton_ROIbaseline[,2])), (as.numeric(WMF_skeleton_ROI6week[,2])))

ggplot(WMF_skeleton_ROI, aes(x=as.numeric(`All ROIs`), fill=type, color=type)) +
  geom_histogram(position="identity", alpha=0.5)

ggplot(WMF_skeleton, aes(type, as.numeric(`All ROIs`))) +
  stat_boxplot(geom = "errorbar") + 
  geom_boxplot( aes(type, as.numeric(`All ROIs`))) +    
  xlab("Type") + 
  ylab("All ROIs")

# wilcox.test((as.numeric(WMF_skeleton_baseline[,2])), (as.numeric(WMF_skeleton_6week[,2])))

# histograms run for both baseline and 6 week for the skeleton based on all ROIs
# Both follwed a normal distribution based on the shapiro test
# t.test shows that there is a difference between means 
```

```{r, echo=FALSE}
data_path_labels = "C:/Users/edwin/Desktop/Volunteer/CANTBIANationalBioba_DATA_LABELS_2020-01-13_0952.xlsx"
labels = read_excel(path=data_path_labels)
# Join two different tables based on subject
# Used fuzzyjoin
colnames(labels)[1] = "subject"
labels = labels %>% drop_na(subject)
WMF_skeleton_ROI_label = regex_inner_join(WMF_skeleton_ROI, labels, by = "subject")
# Create column to differentiate between control and test groups
WMF_skeleton_ROI_label$group = ifelse(grepl("TC{1}", WMF_skeleton_ROI_label$subject.x), "control", "test")

# Run every control group through shapiro test to check normality
for (i in 2:50){
  result = shapiro.test(as.numeric(WMF_skeleton_ROI_label[94:148,i]))
  if(result$p.value>0.05){
    shapiro_control_index = i
  }
}
# A few did not follow normal distribution
# Store which columns follow normality in variable

#Run every test group through shapiro test
for (i in 2:50){
  result = shapiro.test(as.numeric(WMF_skeleton_ROI_label[1:93,i]))
  if(result$p.value>0.05){
    shapiro_test_index = i
  }
}

# Store which columns follow normality in variable

# paired t test for control
# For loop to run through every ROI column
for (i in 2:50){
  test_scores = as.numeric(WMF_skeleton_ROI_label[94:148,i])
  print(ggplot(WMF_skeleton_ROI_label[94:148,], aes(x = type, y = test_scores)) +
    stat_boxplot(geom = "errorbar") +
    geom_boxplot( aes(type, test_scores)) +   
    ggtitle("Paired t-test on Control") +
    xlab("Type") +  
    ylab(colnames(WMF_skeleton_ROI_label)[i]))
}

# Paired t test for test subjects
# For loop to run through every ROI column
for (i in 2:50){
  test_scores = as.numeric(WMF_skeleton_ROI_label[1:93,i])
  print(ggplot(WMF_skeleton_ROI_label[1:93,], aes(x = type, y = test_scores)) +
    stat_boxplot(geom = "errorbar") +
    geom_boxplot( aes(type, test_scores)) +   
    ggtitle("Paired t-test on test") +
    xlab("Type") + 
    ylab(colnames(WMF_skeleton_ROI_label)[i]))
}
# WMF_skeleton_ROI_label$

# Run anova with gender as covariate for control
# Use for loop to go through every single ROI tract
ggplot(WMF_skeleton_ROI_label[94:148,], aes(x = `Gender (Patient Management)`,
                                            y = as.numeric(`All ROIs`),
                                            color = type)) +
  stat_boxplot(geom = "errorbar") +
  geom_boxplot(aes (`Gender (Patient Management)`, as.numeric(`All ROIs`)))

# Anova with gender as covariate for test group
# Use for loop to go through every single ROI tract
ggplot(WMF_skeleton_ROI_label[1:93,], aes(x = `Gender (Patient Management)`,
                                            y = as.numeric(`All ROIs`),
                                            color = type)) +
  stat_boxplot(geom = "errorbar") +
  geom_boxplot(aes (`Gender (Patient Management)`, as.numeric(`All ROIs`)))

# Looking at age to be a covariant
# Subset based on range of ages? 
# ages 10-20, 21-30 etc or split into two groups
WMF_skeleton_ROI_label[which(as.numeric(WMF_skeleton_ROI_label$`Age at time of injury (please enter) (Patient Management)`) > 25),]
```


```{r, echo=FALSE}
FA = read_excel(path=data_path, sheet="FA")
names(FA) = as.matrix(FA[1,])
FA = FA[-1,]
FA[] = lapply(FA, function(x) type.convert(as.character(x)))
FA

MD = read_excel(path=data_path, sheet="MD")
names(MD) = as.matrix(MD[1,])
MD = MD[-1,]
MD[] = lapply(MD, function(x) type.convert(as.character(x)))
MD

AD = read_excel(path=data_path, sheet="AD")
names(AD) = as.matrix(AD[1,])
AD = AD[-1,]
AD[] = lapply(AD, function(x) type.convert(as.character(x)))
AD

RD = read_excel(path=data_path, sheet="RD")
names(RD) = as.matrix(RD[1,])
RD = RD[-1,]
RD[] = lapply(RD, function(x) type.convert(as.character(x)))
RD
```